### ISSUE TITLE
Maximum call stack size exceeded error on big project

### ISSUE THREAD

**Issue by DileSoft** [originjs/vite-plugin-federation#188]
I tried to build with federation big project (I don't know why so many modules, may be because material ui) and got error:

```
✓ 14525 modules transformed.
[originjs:federation] Maximum call stack size exceeded
error during build:
RangeError: Maximum call stack size exceeded
    at addDep (C:\Windows.old-Windows-7\Users\DileSoft\Documents\git\ioBroker.admin\src-rx\node_modules\@originjs\vite-plugin-federation\dist\index.js:2036:25)
    at addDep (C:\Windows.old-Windows-7\Users\DileSoft\Documents\git\ioBroker.admin\src-rx\node_modules\@originjs\vite-plugin-federation\dist\index.js:2036:25)
```

As I think, you use recursive function for list modules, so it get call stack limit.

**Comment by DileSoft** [comment]
I fixed some errors on my code and problem disappears.
