### ISSUE TITLE
Error: Emitted chunks need to have a valid string id, received "undefined"

### ISSUE THREAD

**Issue by polRk** [originjs/vite-plugin-federation#273]
### Versions

- vite-plugin-federation: 1.1.10
- vite: 3.1.0

### Reproduction

```ts
// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    federation({
      name: 'remote-app',
      filename: 'remoteEntry.js',
      exposes: {
        './App': './src/components/App.tsx'
      },
      shared: ['react', 'react-dom','react-router-dom', '@corp/components']
    }),
  ],
  build: {
    minify: false,
    cssCodeSplit: false,
  },
  preview: {
    host: 'localhost',
    port: 3003,
    strictPort: true,
    headers: {
      "Access-Control-Allow-Origin": "*"
    }
  },
  server: {
    port: 3003,
    host: 'localhost',
  }
})
```

```ts
const App: FC = () => {}

export default App;
```

### What is Expected?
Works correctly.

### What is actually happening?

Got an error:

```
vite v3.1.0 building for production...
✓ 0 modules transformed.
[originjs:federation] Emitted chunks need to have a valid string id, received "undefined"
file: /index.html
error during build:
Error: Emitted chunks need to have a valid string id, received "undefined"
    at error (file:///node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at FileEmitter.emitChunk (file:///node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:15579:20)
    at FileEmitter.emitFile (file:///node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:15492:29)
    at Object.emitFile (file:///node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:21949:41)
    at Object.transform (/node_modules/@originjs/vite-plugin-federation/dist/index.js:1551:51)
    at async transform (file:///node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:21928:16)
    at async ModuleLoader.addModuleSource (file:///node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:22153:30)
```

**Comment by polRk** [comment]
Yes, you are right. App was in src folder.
