### ISSUE TITLE
Uncaught SyntaxError: Cannot use import statement outside a module (at remoteEntry.js:1:1)

### ISSUE THREAD

**Issue by ivankorobchuk123** [originjs/vite-plugin-federation#279]
I have a paths error. 

Uncaught SyntaxError: Cannot use import statement outside a module (at remoteEntry.js:1:1)
<img width="475" alt="Screenshot 2022-11-09 at 14 38 13" src="https://user-images.githubusercontent.com/24935631/200859320-651887f8-f08c-4540-8fc0-079391d9c476.png">

**Comment by flyfishzy** [comment]
Try to add type="module" to the script. For example:
```js
<script type="module" src="/src/main.js"></script>
```

**Comment by js-lowes** [comment]
Doesn't work for me. I am experiencing the same problem.

The host in my case is a Webpack and the remote is using Vite.

**Comment by ivankorobchuk123** [comment]
Didn't find a solution. Changed Vite to Webpack

**Comment by adirzoari** [comment]
@js-lowes @ivankorobchuk123  did you find a solution?

**Comment by ivankorobchuk123** [comment]
Sorry, no)

**Comment by js-lowes** [comment]
> @js-lowes @ivankorobchuk123 did you find a solution?

Unfortunately not, but I have tried vite plugin federation in awhile. Best of luck.

**Comment by mjangir** [comment]
This is pretty straightforward. Your remoteEntry.js from Vite is having import statements which are not allowed in browser unless the script tag has **type="module"** attribute. Just set the **type** module on the script tag and it will work fine.

**Comment by adirzoari** [comment]
@mjangir can you check my similar issue here? https://github.com/originjs/vite-plugin-federation/issues/576

**Comment by Lau08** [comment]
Is there an update on this issue? I have also his problem
![image](https://github.com/user-attachments/assets/5e9eee33-4f7d-46bc-957a-453e575c1a01)

**Comment by leonardo-pliskieviski-deel** [comment]
@Lau08 I was able to fix this by adding `type: module` to the parent importer:
```tsx
        remotes: {
          'xyx-module': {
            type: 'module',
            name: 'xyx-module',
            entry: 'http://localhost:3001/remoteEntry.js',
          },
        },
```

**Comment by iskandar17** [comment]
> This is pretty straightforward. Your remoteEntry.js from Vite is having import statements which are not allowed in browser unless the script tag has **type="module"** attribute. Just set the **type** module on the script tag and it will work fine.
> 
> Something like `<script type="module" src="http://localhost:3000/assets/remoteEntry.js" />`

In configurations of the host when using registerRemotes type should be `module` .
