### ISSUE TITLE
Vitejs React and typescript (reference error)

### ISSUE THREAD

**Issue by GeenCo86** [originjs/vite-plugin-federation#318]
I try to get the module federation to run with react on both remote and host and using typescript at all.. 
### Versions (all latest)

- vite-plugin-federation: 1.1.13
- vite: 4.0.3
- react: 18.2.0
- typescript 4.9.3
- 
### Reproduction
[stackblitz example](https://stackblitz.com/edit/github-bje76z-gex1hz?file=host/vite.config.js)

the config on at stackblitz is the same I use

### Steps to reproduce

npm run dev on remote
npm run dev on host

### What is Expected?

the remote component will be displayed on the host side

### What is actually happening?

When the host browser opens there is a console error 

**Uncaught (in promise) ReferenceError: __rf_placeholder__shareScope is not defined
    at Mu (index-2fd87157.js:32:58423)
    at index-2fd87157.js:32:58840**

Also there is a problem referencing the types in my host. If I do it with a definition it is not found. 

```
import React from 'react';

const MyButton: React.FC;

export default MyButton;
```

When I write it like a module definition it is ok:

`declare module 'remote/MyButton';`

But I am not sure if the configuration is fine and the error should tell me something else...

Can you  also give an example for vitejs react and typescript for both sides that is working with the latest versions?

**Comment by GeenCo86** [comment]
After I have researched google and some blogs, now it works (yeah also the fact that only preview mode works). The [Stackblitz](https://stackblitz.com/edit/github-bje76z-gex1hz?file=host/package.json) example is updated.
