### ISSUE TITLE
vue3-advanced-demo启动报错

### ISSUE THREAD

**Issue by AnsGoo** [originjs/vite-plugin-federation#385]
### Versions

- vite-plugin-federation: 
- vite: 4.0.3_@types+node@18.6.4

###  vue3-advanced-demo启动报错
```shell

PS C:\Users\haive\code\vite-plugin-federation\packages\examples\vue3-advanced-demo> pnpm restart

> vue3-advanced-demo@1.0.0 stop C:\Users\haive\code\vite-plugin-federation\packages\examples\vue3-advanced-demo
> kill-port --port 5000,5001,5002

Process on port 5000 killed
Process on port 5001 killed
Process on port 5002 killed

> vue3-advanced-demo@1.0.0 restart C:\Users\haive\code\vite-plugin-federation\packages\examples\vue3-advanced-demo
> pnpm stop & pnpm build & pnpm serve


> vue3-advanced-demo@1.0.0 stop C:\Users\haive\code\vite-plugin-federation\packages\examples\vue3-advanced-demo
> kill-port --port 5000,5001,5002

Process on port 5000 killed
Process on port 5001 killed
Process on port 5002 killed

> vue3-advanced-demo@1.0.0 build C:\Users\haive\code\vite-plugin-federation\packages\examples\vue3-advanced-demo
> pnpm --parallel --filter "./**" build

Scope: 4 of 54 workspace projects
team-blue build$ vue-tsc --noEmit && vite build
team-red build$ vue-tsc --noEmit && vite build
team-green build$ vue-tsc --noEmit && vite build
team-green build: ✘ [ERROR] [plugin externalize-deps] Failed to resolve entry for package "@originjs/vite-plugin-federation". The package may have incorrect main/module/exports specified in its package.json.
team-green build:     ../../../../node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1357:27:
team-green build:       1357 │         let result = await callback({
team-green build:            ╵                            ^
team-green build:     at packageEntryFailure (file:///C:/Users/haive/code/vite-plugin-federation/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:21822:11)
team-green build:     at resolvePackageEntry (file:///C:/Users/haive/code/vite-plugin-federation/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:21819:5)
team-green build:     at tryNodeResolve (file:///C:/Users/haive/code/vite-plugin-federation/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:21557:20)
team-green build:     at file:///C:/Users/haive/code/vite-plugin-federation/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:62013:40
team-green build:     at requestCallbacks.on-resolve (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1357:28)
team-green build:     at handleRequest (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:723:19)
team-green build:     at handleIncomingPacket (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:745:7)
team-green build:     at Socket.readFromStdout (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:673:7)
team-green build:     at Socket.emit (node:events:513:28)
team-green build:     at addChunk (node:internal/streams/readable:324:12)
team-green build:   This error came from the "onResolve" callback registered here:
team-green build:     ../../../../node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1281:20:
team-green build:       1281 │       let promise = setup({
team-green build:            ╵                     ^
team-green build:     at setup (file:///C:/Users/haive/code/vite-plugin-federation/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:62002:27)
team-green build:     at handlePlugins (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1281:21)
team-green build:     at buildOrServeImpl (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:970:5)
team-green build:     at Object.buildOrServe (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:776:5)
team-green build:     at C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:2117:17
team-green build:     at new Promise (<anonymous>)
team-green build:     at Object.build (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:2116:14)
team-green build:     at build (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1963:51)
team-green build:     at bundleConfigFile (file:///C:/Users/haive/code/vite-plugin-federation/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:61966:26)
team-green build:   The plugin "externalize-deps" was triggered by this import
team-green build:     vite.config.ts:3:23:
team-green build:       3 │ import federation from '@originjs/vite-plugin-federation'
team-green build:         ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
team-green build: failed to load config from C:\Users\haive\code\vite-plugin-federation\packages\examples\vue3-advanced-demo\team-green\vite.config.ts
team-green build: error during build:
team-green build: Error: Build failed with 1 error:
team-green build: ../../../../node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1357:27: ERROR: [plugin: externalize-deps] Failed to resolve entry for package "@originjs/vite-plugin-federation". The package may have incorrect main/module/exports specified in its package.json.
team-green build:     at failureErrorWithLog (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1596:15)
team-green build:     at C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1052:28
team-green build:     at runOnEndCallbacks (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1468:61)
team-green build:     at buildResponseToResult (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1050:7)
team-green build:     at C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1162:14
team-green build:     at responseCallbacks.<computed> (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:697:9)
team-green build:     at handleIncomingPacket (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:752:9)
team-green build:     at Socket.readFromStdout (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:673:7)
team-green build:     at Socket.emit (node:events:513:28)
team-green build:     at addChunk (node:internal/streams/readable:324:12)
team-green build: Failed
C:\Users\haive\code\vite-plugin-federation\packages\examples\vue3-advanced-demo\team-green:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  team-green@0.0.0 build: `vue-tsc --noEmit && vite build`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.

> vue3-advanced-demo@1.0.0 serve C:\Users\haive\code\vite-plugin-federation\packages\examples\vue3-advanced-demo
> pnpm --parallel --filter "./**" serve

Scope: 4 of 54 workspace projects
team-blue serve$ vite preview --port 5002 --strictPort
team-green serve$ vite preview --port 5001 --strictPort
team-red serve$ vite preview --port 5000 --strictPort
team-green serve: ✘ [ERROR] [plugin externalize-deps] Failed to resolve entry for package "@originjs/vite-plugin-federation". The package may have incorrect main/module/exports specified in its package.json.
team-green serve:     ../../../../node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1357:27:
team-green serve:       1357 │         let result = await callback({
team-blue serve: ✘ [ERROR] [plugin externalize-deps] Failed to resolve entry for package "@originjs/vite-plugin-federation". The package may have incorrect main/module/exports specified in its package.json.
team-blue serve:     ../../../../node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1357:27:
team-blue serve:       1357 │         let result = await callback({
team-blue serve:            ╵                            ^
team-blue serve:     at packageEntryFailure (file:///C:/Users/haive/code/vite-plugin-federation/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:21822:11)
team-blue serve:     at resolvePackageEntry (file:///C:/Users/haive/code/vite-plugin-federation/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:21819:5)
team-blue serve:     at tryNodeResolve (file:///C:/Users/haive/code/vite-plugin-federation/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:21557:20)
team-blue serve:     at file:///C:/Users/haive/code/vite-plugin-federation/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:62013:40
team-blue serve:     at requestCallbacks.on-resolve (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1357:28)
team-blue serve:     at handleRequest (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:723:19)
team-blue serve:     at handleIncomingPacket (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:745:7)
team-blue serve:     at Socket.readFromStdout (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:673:7)
team-blue serve:     at Socket.emit (node:events:513:28)
team-blue serve:     at addChunk (node:internal/streams/readable:324:12)
team-blue serve:   This error came from the "onResolve" callback registered here:
team-blue serve:     ../../../../node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1281:20:
team-blue serve:       1281 │       let promise = setup({
team-blue serve:            ╵                     ^
team-blue serve:     at setup (file:///C:/Users/haive/code/vite-plugin-federation/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:62002:27)
team-blue serve:     at handlePlugins (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1281:21)
team-blue serve:     at buildOrServeImpl (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:970:5)
team-blue serve:     at Object.buildOrServe (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:776:5)
team-blue serve:     at C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:2117:17
team-blue serve:     at new Promise (<anonymous>)
team-blue serve:     at Object.build (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:2116:14)
team-blue serve:     at build (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1963:51)
team-blue serve:     at bundleConfigFile (file:///C:/Users/haive/code/vite-plugin-federation/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:61966:26)
team-blue serve:   The plugin "externalize-deps" was triggered by this import
team-blue serve:     vite.config.ts:3:23:
team-blue serve:       3 │ import federation from '@originjs/vite-plugin-federation'
team-blue serve:         ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
team-green serve:            ╵                            ^
team-green serve:     at packageEntryFailure (file:///C:/Users/haive/code/vite-plugin-federation/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:21822:11)
team-green serve:     at resolvePackageEntry (file:///C:/Users/haive/code/vite-plugin-federation/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:21819:5)
team-green serve:     at tryNodeResolve (file:///C:/Users/haive/code/vite-plugin-federation/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:21557:20)
team-green serve:     at file:///C:/Users/haive/code/vite-plugin-federation/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:62013:40
team-green serve:     at requestCallbacks.on-resolve (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1357:28)
team-green serve:     at handleRequest (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:723:19)
team-green serve:     at handleIncomingPacket (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:745:7)
team-green serve:     at Socket.readFromStdout (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:673:7)
team-green serve:     at Socket.emit (node:events:513:28)
team-green serve:     at addChunk (node:internal/streams/readable:324:12)
team-green serve:   This error came from the "onResolve" callback registered here:
team-green serve:     ../../../../node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1281:20:
team-green serve:       1281 │       let promise = setup({
team-green serve:            ╵                     ^
team-green serve:     at setup (file:///C:/Users/haive/code/vite-plugin-federation/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:62002:27)
team-green serve:     at handlePlugins (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1281:21)
team-green serve:     at buildOrServeImpl (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:970:5)
team-green serve:     at Object.buildOrServe (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:776:5)
team-green serve:     at C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:2117:17
team-green serve:     at new Promise (<anonymous>)
team-green serve:     at Object.build (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:2116:14)
team-green serve:     at build (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1963:51)
team-green serve:     at bundleConfigFile (file:///C:/Users/haive/code/vite-plugin-federation/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:61966:26)
team-green serve:   The plugin "externalize-deps" was triggered by this import
team-green serve:     vite.config.ts:3:23:
team-green serve:       3 │ import federation from '@originjs/vite-plugin-federation'
team-green serve:         ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
team-green serve: failed to load config from C:\Users\haive\code\vite-plugin-federation\packages\examples\vue3-advanced-demo\team-green\vite.config.ts
team-green serve: error when starting preview server:
team-green serve: Error: Build failed with 1 error:
team-green serve: ../../../../node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1357:27: ERROR: [plugin: externalize-deps] Failed to resolve entry for package "@originjs/vite-plugin-federation". The package may have incorrect main/module/exports specified in its package.json.
team-green serve:     at failureErrorWithLog (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1596:15)
team-green serve:     at C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1052:28
team-green serve:     at runOnEndCallbacks (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1468:61)
team-green serve:     at buildResponseToResult (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1050:7)
team-green serve:     at C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1162:14
team-green serve:     at responseCallbacks.<computed> (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:697:9)
team-green serve:     at handleIncomingPacket (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:752:9)
team-green serve:     at Socket.readFromStdout (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:673:7)
team-green serve:     at Socket.emit (node:events:513:28)
team-green serve:     at addChunk (node:internal/streams/readable:324:12)
team-red serve: ✘ [ERROR] [plugin externalize-deps] Failed to resolve entry for package "@originjs/vite-plugin-federation". The package may have incorrect main/module/exports specified in its package.json.
team-red serve:     ../../../../node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1357:27:
team-red serve:       1357 │         let result = await callback({
team-red serve:            ╵                            ^
team-red serve:     at packageEntryFailure (file:///C:/Users/haive/code/vite-plugin-federation/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:21822:11)
team-red serve:     at resolvePackageEntry (file:///C:/Users/haive/code/vite-plugin-federation/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:21819:5)
team-red serve:     at tryNodeResolve (file:///C:/Users/haive/code/vite-plugin-federation/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:21557:20)
team-red serve:     at file:///C:/Users/haive/code/vite-plugin-federation/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:62013:40
team-red serve:     at requestCallbacks.on-resolve (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1357:28)
team-red serve:     at handleRequest (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:723:19)
team-red serve:     at handleIncomingPacket (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:745:7)
team-red serve:     at Socket.readFromStdout (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:673:7)
team-red serve:     at Socket.emit (node:events:513:28)
team-red serve:     at addChunk (node:internal/streams/readable:324:12)
team-red serve:   This error came from the "onResolve" callback registered here:
team-red serve:     ../../../../node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1281:20:
team-red serve:       1281 │       let promise = setup({
team-red serve:            ╵                     ^
team-red serve:     at setup (file:///C:/Users/haive/code/vite-plugin-federation/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:62002:27)
team-red serve:     at handlePlugins (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1281:21)
team-red serve:     at buildOrServeImpl (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:970:5)
team-red serve:     at Object.buildOrServe (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:776:5)
team-red serve:     at C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:2117:17
team-red serve:     at new Promise (<anonymous>)
team-red serve:     at Object.build (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:2116:14)
team-red serve:     at build (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1963:51)
team-red serve:     at bundleConfigFile (file:///C:/Users/haive/code/vite-plugin-federation/node_modules/.pnpm/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:61966:26)
team-red serve:   The plugin "externalize-deps" was triggered by this import
team-red serve:     vite.config.ts:3:23:
team-red serve:       3 │ import federation from "@originjs/vite-plugin-federation"
team-red serve:         ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
team-red serve: failed to load config from C:\Users\haive\code\vite-plugin-federation\packages\examples\vue3-advanced-demo\team-red\vite.config.ts
team-red serve: error when starting preview server:
team-red serve: Error: Build failed with 1 error:
team-red serve: ../../../../node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1357:27: ERROR: [plugin: externalize-deps] Failed to resolve entry for package "@originjs/vite-plugin-federation". The package may have incorrect main/module/exports specified in its package.json.
team-red serve:     at failureErrorWithLog (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1596:15)
team-red serve:     at C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1052:28
team-red serve:     at runOnEndCallbacks (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1468:61)
team-red serve:     at buildResponseToResult (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1050:7)
team-red serve:     at C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1162:14
team-red serve:     at responseCallbacks.<computed> (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:697:9)
team-red serve:     at handleIncomingPacket (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:752:9)
team-red serve:     at Socket.readFromStdout (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:673:7)
team-red serve:     at Socket.emit (node:events:513:28)
team-red serve:     at addChunk (node:internal/streams/readable:324:12)
team-blue serve: failed to load config from C:\Users\haive\code\vite-plugin-federation\packages\examples\vue3-advanced-demo\team-blue\vite.config.ts
team-blue serve: error when starting preview server:
team-blue serve: Error: Build failed with 1 error:
team-blue serve: ../../../../node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1357:27: ERROR: [plugin: externalize-deps] Failed to resolve entry for package "@originjs/vite-plugin-federation". The package may have incorrect main/module/exports specified in its package.json.
team-blue serve:     at failureErrorWithLog (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1596:15)
team-blue serve:     at C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1052:28
team-blue serve:     at runOnEndCallbacks (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1468:61)
team-blue serve:     at buildResponseToResult (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1050:7)
team-blue serve:     at C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1162:14
team-blue serve:     at responseCallbacks.<computed> (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:697:9)
team-blue serve:     at handleIncomingPacket (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:752:9)
team-blue serve:     at Socket.readFromStdout (C:\Users\haive\code\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:673:7)
team-blue serve:     at Socket.emit (node:events:513:28)
team-blue serve:     at addChunk (node:internal/streams/readable:324:12)
team-red serve: Failed
C:\Users\haive\code\vite-plugin-federation\packages\examples\vue3-advanced-demo\team-red:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  team-red@0.0.0 serve: `vite preview --port 5000 --strictPort`
Exit status 1
team-blue serve: Failed
team-green serve: Failed
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by krank56** [comment]
Try running `pnpm --max-old-space-size=8192 restart`.

**Comment by krank56** [comment]
#391 Also this PR may help

**Comment by ruleeeer** [comment]
> > Try running `pnpm --max-old-space-size=8192 restart`. This flag increases the memory available for node.js default is 512Mb if I recall correctly, you can try the PR bellow to run the examples without the lib process
> 
> 似乎不是这个原因，`pnpm --max-old-space-size=8192 restart` 没有任何效果

Have you built a local library first?

**Comment by krank56** [comment]
> > Try running `pnpm --max-old-space-size=8192 restart`. This flag increases the memory available for node.js default is 512Mb if I recall correctly, you can try the PR bellow to run the examples without the lib process
> 
> 似乎不是这个原因，`pnpm --max-old-space-size=8192 restart` 没有任何效果

#392 Try this pr instead, it will skip the build process for the library and use the npm package instead

**Comment by Aaronius** [comment]
I ran into this same error. What @ruleeeer is saying, I believe, is that you need to go to the vite-plugin-federation project root directory, run `pnpm install`, then `pnpm build`. At that point, you can go back into the `examples/vue3-demo-esm` directory, run `pnpm install`, then `pnpm build`, then `pnpm serve`, and it should work. It worked for me, anyway.

Running `pnpm --max-old-space-size=8192 restart` won't help and there's no need to do what's described in https://github.com/originjs/vite-plugin-federation/pull/392.
