### ISSUE TITLE
Uncaught ReferenceError: __rf_placeholder__shareScope is not defined

### ISSUE THREAD

**Issue by bramdeba** [originjs/vite-plugin-federation#395]
### Versions

- vite-plugin-federation: 1.2.2
- vite: 4.0.1

### Reproduction

https://github.com/bramdeba/vite-plugin-federation-issue

<details open>
<summary>Additional Details</summary>
<br>
<img width="626" alt="image" src="https://user-images.githubusercontent.com/14555156/230726220-27c1df93-83b3-4f8b-9583-3adc46c71ce7.png">
</details>

### Steps to reproduce
* `git clone https://github.com/bramdeba/vite-plugin-federation-issue`
* navigate to project directory with terminal
* run `yarn` to install dependencies
* run `yarn serve:host` and `yarn serve:remote` simultaneously
* navigate to `http://localhost:4300`

### What is Expected?
Expected is that you would see a <button/>-component, imported from the remote module.

### What is actually happening?
Nothing is rendered, and you get an error in the console:
```Uncaught ReferenceError: __rf_placeholder__shareScope is not defined
    at Ki (index-38bc938c.js:40:58371)
    at index-38bc938c.js:40:58803
Ki @ index-38bc938c.js:40
(anonymous) @ index-38bc938c.js:40
```

**Comment by salindae25** [comment]
In case you want a workaround put the following in **index.html** 
`<script>
const __rf_placeholder__shareScope={}
</script>
`

**Comment by ureciocais** [comment]
Same issue here

**Comment by oychao** [comment]
same here

**Comment by mossen** [comment]
I have 1 remote and 2 hosts, this issue only happens on one of the hosts.
I have same versions and configs.

this part of the generated code is missing for the host where I receive the error:

```
function get(name, remoteFrom) {
                    return __federation_import(name).then(module => () => {
                        if (remoteFrom === 'webpack') {
                            return Object.prototype.toString.call(module).indexOf('Module') > -1 && module.default ? module.default : module
                        }
                        return module
                    })
                }

                const wrapShareModule = remoteFrom => {
                    return {
                        'react':{'18.2.0':{get:()=>get('./__federation_shared_react.js', remoteFrom), loaded:1}}
                    }
                };
```

error:
```
dex-b09da57a.js:65912 Uncaught ReferenceError: __rf_placeholder__shareScope is not defined
    at wrapShareModule (index-b09da57a.js:65912:25)
    at index-b09da57a.js:65939:64
```

**Comment by mossen** [comment]
Resolved it!

Seems this is related to the `tsconfig.json` where `baseUrl` is not matching the `paths`.

```
{
  "compilerOptions": {
    "target": "es6",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "baseUrl": "./src",
    "paths": {
      "src/*": ["*"],
    },
    "jsx": "react-jsx"
  },
  "include": ["src"],
  "exclude": ["node_modules"]
}
```

**Comment by He110te4m** [comment]
> 

I have the same problem. The direction I'm going in is virtual modules.

The plugin uses `===` when resolving virtual module file names.

In fact, it is possible for a project to have a module name with an absolute path to the project that does not match, so there is no text substitution.

(see link)[https://github.com/originjs/vite-plugin-federation/discussions/159#discussioncomment-5655600]

**Comment by stefan-karlsson** [comment]
@bramdeba remove the `viteTsConfigPaths({ root: '../../' })` in your host application and you should be fine.

https://github.com/bramdeba/vite-plugin-federation-issue/blob/3d3ce8563f9be5d0b9e665f507fa8fb766ada8df/apps/host/vite.config.ts#L22C5-L24C8

**Comment by nemonemi** [comment]
> @bramdeba remove the `viteTsConfigPaths({ root: '../../' })` in your host application and you should be fine.
> 
> https://github.com/bramdeba/vite-plugin-federation-issue/blob/3d3ce8563f9be5d0b9e665f507fa8fb766ada8df/apps/host/vite.config.ts#L22C5-L24C8

That is not an option in my case, because the build fails with 
```ts
vite v4.3.9 building for development...
✓ 21 modules transformed.
✓ built in 472ms
[originjs:federation] Cannot read properties of undefined (reading 'config')
file: virtual:__federation__

 >  NX   Cannot read properties of undefined (reading 'config')

```

**Comment by sandropimenta-hotmart** [comment]
Me too have this problem! 

I'm use remote example vite + react (https://github.com/originjs/vite-plugin-federation/blob/main/packages/examples/react-vite/remote/vite.config.js#L13). 

And my project host called button component, my config vite bellow: 

plugins: [
      react(),
      graphql(),
      tsconfigPaths(),
      viteCompression(),
      federation({
        name: 'app',
        remotes: {
          remoteApp: 'http://localhost:5001/assets/remoteEntry.js',
        },
        shared: ['react', 'react-dom'],
      }),
    ],
    build: {
      modulePreload: false,
      target: 'esnext',
      minify: false,
      cssCodeSplit: false,
      sourcemap: true,
    },

**Comment by marcin-kopanski** [comment]
> Resolved it!
> 
> Seems this is related to the `tsconfig.json` where `baseUrl` is not matching the `paths`.
> 
> ```
> {
>   "compilerOptions": {
>     "target": "es6",
>     "lib": ["dom", "dom.iterable", "esnext"],
>     "allowJs": true,
>     "skipLibCheck": true,
>     "esModuleInterop": true,
>     "allowSyntheticDefaultImports": true,
>     "strict": true,
>     "forceConsistentCasingInFileNames": true,
>     "noFallthroughCasesInSwitch": true,
>     "module": "esnext",
>     "moduleResolution": "node",
>     "resolveJsonModule": true,
>     "isolatedModules": true,
>     "noEmit": true,
>     "baseUrl": "./src",
>     "paths": {
>       "src/*": ["*"],
>     },
>     "jsx": "react-jsx"
>   },
>   "include": ["src"],
>   "exclude": ["node_modules"]
> }
> ```

Thanks!!

**Comment by lewisloofis** [comment]
Any solution besides this? I use this plugin on monorepo setup so I cannot remove `viteTsConfigPaths` configuration from my vite

> @bramdeba remove the `viteTsConfigPaths({ root: '../../' })` in your host application and you should be fine.
> 
> https://github.com/bramdeba/vite-plugin-federation-issue/blob/3d3ce8563f9be5d0b9e665f507fa8fb766ada8df/apps/host/vite.config.ts#L22C5-L24C8

**Comment by marcin-kopanski** [comment]
> Resolved it!
> 
> Seems this is related to the `tsconfig.json` where `baseUrl` is not matching the `paths`.
> 
> ```
> {
>   "compilerOptions": {
>     "target": "es6",
>     "lib": ["dom", "dom.iterable", "esnext"],
>     "allowJs": true,
>     "skipLibCheck": true,
>     "esModuleInterop": true,
>     "allowSyntheticDefaultImports": true,
>     "strict": true,
>     "forceConsistentCasingInFileNames": true,
>     "noFallthroughCasesInSwitch": true,
>     "module": "esnext",
>     "moduleResolution": "node",
>     "resolveJsonModule": true,
>     "isolatedModules": true,
>     "noEmit": true,
>     "baseUrl": "./src",
>     "paths": {
>       "src/*": ["*"],
>     },
>     "jsx": "react-jsx"
>   },
>   "include": ["src"],
>   "exclude": ["node_modules"]
> }
> ```

Thanks!

**Comment by okkpp** [comment]
> <img alt="image" width="973" src="https://private-user-images.githubusercontent.com/16275856/317626001-360af058-13a2-4159-a081-8af715e37db5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTI0NTkzNjMsIm5iZiI6MTc1MjQ1OTA2MywicGF0aCI6Ii8xNjI3NTg1Ni8zMTc2MjYwMDEtMzYwYWYwNTgtMTNhMi00MTU5LWEwODEtOGFmNzE1ZTM3ZGI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzE0VDAyMTEwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4ZmEzYjBhODc0MGE0YjNiMWU1ZDkxYmE5YmViZjg2MGNlNzU2MDUyMzk5YTI3MjBkNTFkOThmNjUxODI0ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ri6l11YjLsuUJdNRkFNwKUSJIK0LZB6n3yhJqpS2psY"> <img alt="image" width="790" src="https://private-user-images.githubusercontent.com/16275856/317626707-20dcc2e0-19fe-48b8-9976-ca958a0804a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTI0NTkzNjMsIm5iZiI6MTc1MjQ1OTA2MywicGF0aCI6Ii8xNjI3NTg1Ni8zMTc2MjY3MDctMjBkY2MyZTAtMTlmZS00OGI4LTk5NzYtY2E5NThhMDgwNGE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzE0VDAyMTEwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZGVhZGRmNmQyOWMyZDA1ZTIzMGEzMWJkNTg3NmEzNzEwZWM4YmUwYmU0ZjY1YjE0OGY5YjMzMzE5NjViMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.M3QaoMxNrqwTPoXfr2wcSQh7ue0GJzeB6G5cUsuimVk">
> federation({ name: 'host-app', remotes: { "remote-xxx":"http://localhost:5011/assets/remoteEntry.js", }, shared: ['vue', 'pinia'] }) 我遇到的情况是 remotes 必须要有值，才会被当成宿主app，当实际上我只需要动态加载，remotes不需要赋值 🙅🏻‍♀️ -- The situation I encountered is that remotes must have a value before they can be regarded as the host app. In fact, I only need to load dynamically, and remotes do not need to be assigned a value.

same issue and resovled by add a useless remote like this :
```js
      federation({
        remotes: {
          "None": ""
        },
        shared: ["vue"]
      })
```

**Comment by FriedJannik** [comment]
> > <img alt="image" width="973" src="https://private-user-images.githubusercontent.com/16275856/317626001-360af058-13a2-4159-a081-8af715e37db5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTI0NTkzNjMsIm5iZiI6MTc1MjQ1OTA2MywicGF0aCI6Ii8xNjI3NTg1Ni8zMTc2MjYwMDEtMzYwYWYwNTgtMTNhMi00MTU5LWEwODEtOGFmNzE1ZTM3ZGI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzE0VDAyMTEwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4ZmEzYjBhODc0MGE0YjNiMWU1ZDkxYmE5YmViZjg2MGNlNzU2MDUyMzk5YTI3MjBkNTFkOThmNjUxODI0ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ri6l11YjLsuUJdNRkFNwKUSJIK0LZB6n3yhJqpS2psY"> <img alt="image" width="790" src="https://private-user-images.githubusercontent.com/16275856/317626707-20dcc2e0-19fe-48b8-9976-ca958a0804a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTI0NTkzNjMsIm5iZiI6MTc1MjQ1OTA2MywicGF0aCI6Ii8xNjI3NTg1Ni8zMTc2MjY3MDctMjBkY2MyZTAtMTlmZS00OGI4LTk5NzYtY2E5NThhMDgwNGE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzE0VDAyMTEwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZGVhZGRmNmQyOWMyZDA1ZTIzMGEzMWJkNTg3NmEzNzEwZWM4YmUwYmU0ZjY1YjE0OGY5YjMzMzE5NjViMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.M3QaoMxNrqwTPoXfr2wcSQh7ue0GJzeB6G5cUsuimVk">
> > federation({ name: 'host-app', remotes: { "remote-xxx":"http://localhost:5011/assets/remoteEntry.js", }, shared: ['vue', 'pinia'] }) 我遇到的情况是 remotes 必须要有值，才会被当成宿主app，当实际上我只需要动态加载，remotes不需要赋值 🙅🏻‍♀️ -- The situation I encountered is that remotes must have a value before they can be regarded as the host app. In fact, I only need to load dynamically, and remotes do not need to be assigned a value.
> 
> same issue and resovled by add a useless remote like this :
> 
>       federation({
>         remotes: {
>           "None": ""
>         },
>         shared: ["vue"]
>       })

This actually works. Wow.
