### ISSUE TITLE
Runing demo fails

### ISSUE THREAD

**Issue by jmail** [originjs/vite-plugin-federation#636]
I cloned repo to see how it works and just run tried to run vite-plugin-federation\packages\examples\vue3-advanced-demo

```
pnpm i
pnpm restart
```

it didnt even started 

```
PS D:\usr\htdocs\vite-plugin-federation\packages\examples\vue3-advanced-demo> pnpm i
Scope: all 58 workspace projects
../../..                                 | +984 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Downloading typescript@4.9.4: 11.62 MB/11.62 MB, done
Downloading element-plus@2.2.15: 7.88 MB/7.88 MB, done
Downloading @swc/core-win32-x64-msvc@1.2.224: 25.86 MB/25.86 MB, done
../../..                                 | Progress: resolved 984, reused 0, downloaded 979, added 984, done
../../../node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild: Running postinstall script, done in 2.4s
../../../node_modules/.pnpm/vue-demi@0.13.1_vue@3.2.45/node_modules/vue-demi: Running postinstall script, done in 333ms
../../../node_modules/.pnpm/@swc+core@1.2.224/node_modules/@swc/core: Running postinstall script, done in 254ms
../../../node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild: Running postinstall script, done in 3.4s
../../../node_modules/.pnpm/playwright-chromium@1.24.2/node_modules/playwright-chromium: Running install script, done in 45.4s

devDependencies:
+ @originjs/vite-plugin-federation 1.3.6 <- ..\..\lib
+ kill-port 2.0.1
+ vite-plugin-css-injected-by-js 2.2.0

../../.. postinstall$ npx playwright install
[16 lines collapsed]
│ |■■■■■■■■■■■■■■■■                                                                |  20% of 43.2 Mb
│ |■■■■■■■■■■■■■■■■■■■■■■■■                                                        |  30% of 43.2 Mb
│ |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                                |  40% of 43.2 Mb
│ |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                        |  50% of 43.2 Mb
│ |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                |  60% of 43.2 Mb
│ |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                        |  70% of 43.2 Mb
│ |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                |  80% of 43.2 Mb
│ |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■        |  90% of 43.2 Mb
│ |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■| 100% of 43.2 Mb
│ Webkit 16.0 (playwright build v1683) downloaded to C:\Users\admin\AppData\Local\ms-playwright\webkit-1683
└─ Done in 41.2s
../../.. prepare$ husky install
│ husky - Git hooks installed
└─ Done in 260ms
Done in 2m 16.2s
PS D:\usr\htdocs\vite-plugin-federation\packages\examples\vue3-advanced-demo> pnpm restart

> vue3-advanced-demo@1.0.0 stop D:\usr\htdocs\vite-plugin-federation\packages\examples\vue3-advanced-demo
> kill-port --port 5000,5001,5002

Process on port 5001 killed
Process on port 5000 killed
Process on port 5002 killed

> vue3-advanced-demo@1.0.0 restart D:\usr\htdocs\vite-plugin-federation\packages\examples\vue3-advanced-demo
> pnpm stop & pnpm build & pnpm serve


> vue3-advanced-demo@1.0.0 stop D:\usr\htdocs\vite-plugin-federation\packages\examples\vue3-advanced-demo
> kill-port --port 5000,5001,5002

Process on port 5000 killed
Process on port 5001 killed
Process on port 5002 killed

> vue3-advanced-demo@1.0.0 build D:\usr\htdocs\vite-plugin-federation\packages\examples\vue3-advanced-demo
> pnpm --parallel --filter "./**" build

Scope: 4 of 58 workspace projects
team-green build$ vue-tsc --noEmit && vite build
team-blue build$ vue-tsc --noEmit && vite build
team-red build$ vue-tsc --noEmit && vite build
team-green build: ✘ [ERROR] [plugin externalize-deps] Failed to resolve entry for package "@originjs/vite-plugin-federation". The package may have incorrect main/module/exports specified in its package.json.
team-green build:     ../../../../node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1357:27:
team-green build:       1357 │         let result = await callback({
team-green build:            ╵                            ^
team-green build:     at packageEntryFailure (file:///D:/usr/htdocs/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:21837:11)
team-green build:     at resolvePackageEntry (file:///D:/usr/htdocs/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:21834:5)
team-green build:     at tryNodeResolve (file:///D:/usr/htdocs/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:21572:20)
team-green build:     at file:///D:/usr/htdocs/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:62039:40
team-green build:     at requestCallbacks.on-resolve (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1357:28)
team-green build:     at handleRequest (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:723:19)
team-green build:     at handleIncomingPacket (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:745:7)
team-green build:     at Socket.readFromStdout (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:673:7)
team-green build:     at Socket.emit (node:events:520:28)
team-green build:     at addChunk (node:internal/streams/readable:559:12)
team-green build:   This error came from the "onResolve" callback registered here:
team-green build:     ../../../../node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1281:20:
team-green build:       1281 │       let promise = setup({
team-green build:            ╵                     ^
team-green build:     at setup (file:///D:/usr/htdocs/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:62028:27)
team-green build:     at handlePlugins (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1281:21)
team-green build:     at buildOrServeImpl (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:970:5)
team-green build:     at Object.buildOrServe (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:776:5)
team-green build:     at D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:2117:17
team-green build:     at new Promise (<anonymous>)
team-green build:     at Object.build (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:2116:14)
team-green build:     at build (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1963:51)
team-green build:     at bundleConfigFile (file:///D:/usr/htdocs/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:61992:26)
team-green build:   The plugin "externalize-deps" was triggered by this import
team-green build:     vite.config.ts:3:23:
team-green build:       3 │ import federation from '@originjs/vite-plugin-federation'
team-green build:         ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
team-green build: failed to load config from D:\usr\htdocs\vite-plugin-federation\packages\examples\vue3-advanced-demo\team-green\vite.config.ts
team-green build: error during build:
team-green build: Error: Build failed with 1 error:
team-green build: ../../../../node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1357:27: ERROR: [plugin: externalize-deps] Failed to resolve entry for package "@originjs/vite-plugin-federation". The package may have incorrect main/module/exports specified in its package.json.
team-green build:     at failureErrorWithLog (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1596:15)
team-green build:     at D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1052:28
team-green build:     at runOnEndCallbacks (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1468:61)
team-green build:     at buildResponseToResult (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1050:7)
team-green build:     at D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1162:14
team-green build:     at responseCallbacks.<computed> (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:697:9)
team-green build:     at handleIncomingPacket (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:752:9)
team-green build:     at Socket.readFromStdout (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:673:7)
team-green build:     at Socket.emit (node:events:520:28)
team-green build:     at addChunk (node:internal/streams/readable:559:12)
team-green build: Failed
D:\usr\htdocs\vite-plugin-federation\packages\examples\vue3-advanced-demo\team-green:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  team-green@0.0.0 build: `vue-tsc --noEmit && vite build`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.

> vue3-advanced-demo@1.0.0 serve D:\usr\htdocs\vite-plugin-federation\packages\examples\vue3-advanced-demo
> pnpm --parallel --filter "./**" serve

Scope: 4 of 58 workspace projects
team-green serve$ vite preview --port 5001 --strictPort
team-blue serve$ vite preview --port 5002 --strictPort
team-red serve$ vite preview --port 5000 --strictPort
team-green serve: ✘ [ERROR] [plugin externalize-deps] Failed to resolve entry for package "@originjs/vite-plugin-federation". The package may have incorrect main/module/exports specified in its package.json.
team-green serve:     ../../../../node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1357:27:
team-green serve:       1357 │         let result = await callback({
team-green serve:            ╵                            ^
team-green serve:     at packageEntryFailure (file:///D:/usr/htdocs/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:21837:11)
team-green serve:     at resolvePackageEntry (file:///D:/usr/htdocs/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:21834:5)
team-green serve:     at tryNodeResolve (file:///D:/usr/htdocs/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:21572:20)
team-green serve:     at file:///D:/usr/htdocs/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:62039:40
team-green serve:     at requestCallbacks.on-resolve (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1357:28)
team-green serve:     at handleRequest (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:723:19)
team-green serve:     at handleIncomingPacket (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:745:7)
team-green serve:     at Socket.readFromStdout (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:673:7)
team-green serve:     at Socket.emit (node:events:520:28)
team-green serve:     at addChunk (node:internal/streams/readable:559:12)
team-green serve:   This error came from the "onResolve" callback registered here:
team-green serve:     ../../../../node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1281:20:
team-green serve:       1281 │       let promise = setup({
team-green serve:            ╵                     ^
team-green serve:     at setup (file:///D:/usr/htdocs/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:62028:27)
team-green serve:     at handlePlugins (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1281:21)
team-green serve:     at buildOrServeImpl (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:970:5)
team-green serve:     at Object.buildOrServe (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:776:5)
team-green serve:     at D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:2117:17
team-green serve:     at new Promise (<anonymous>)
team-green serve:     at Object.build (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:2116:14)
team-green serve:     at build (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1963:51)
team-green serve:     at bundleConfigFile (file:///D:/usr/htdocs/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:61992:26)
team-green serve:   The plugin "externalize-deps" was triggered by this import
team-green serve:     vite.config.ts:3:23:
team-green serve:       3 │ import federation from '@originjs/vite-plugin-federation'
team-green serve:         ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
team-green serve: failed to load config from D:\usr\htdocs\vite-plugin-federation\packages\examples\vue3-advanced-demo\team-green\vite.config.ts
team-green serve: error when starting preview server:
team-green serve: Error: Build failed with 1 error:
team-green serve: ../../../../node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1357:27: ERROR: [plugin: externalize-deps] Failed to resolve entry for package "@originjs/vite-plugin-federation". The package may have incorrect main/module/exports specified in its package.json.
team-green serve:     at failureErrorWithLog (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1596:15)
team-green serve:     at D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1052:28
team-green serve:     at runOnEndCallbacks (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1468:61)
team-green serve:     at buildResponseToResult (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1050:7)
team-green serve:     at D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1162:14
team-green serve:     at responseCallbacks.<computed> (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:697:9)
team-green serve:     at handleIncomingPacket (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:752:9)
team-green serve:     at Socket.readFromStdout (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:673:7)
team-green serve:     at Socket.emit (node:events:520:28)
team-green serve:     at addChunk (node:internal/streams/readable:559:12)
team-green serve: Failed
D:\usr\htdocs\vite-plugin-federation\packages\examples\vue3-advanced-demo\team-green:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  team-green@0.0.0 serve: `vite preview --port 5001 --strictPort`
Exit status 1
team-blue serve: ✘ [ERROR] [plugin externalize-deps] Failed to resolve entry for package "@originjs/vite-plugin-federation". The package may have incorrect main/module/exports specified in its package.json.
team-blue serve:     ../../../../node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1357:27:
team-blue serve:       1357 │         let result = await callback({
team-blue serve:            ╵                            ^
team-blue serve:     at packageEntryFailure (file:///D:/usr/htdocs/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:21837:11)
team-blue serve:     at resolvePackageEntry (file:///D:/usr/htdocs/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:21834:5)
team-blue serve:     at tryNodeResolve (file:///D:/usr/htdocs/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:21572:20)
team-blue serve:     at file:///D:/usr/htdocs/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:62039:40
team-blue serve:     at requestCallbacks.on-resolve (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1357:28)
team-blue serve:     at handleRequest (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:723:19)
team-blue serve:     at handleIncomingPacket (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:745:7)
team-blue serve:     at Socket.readFromStdout (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:673:7)
team-blue serve:     at Socket.emit (node:events:520:28)
team-blue serve:     at addChunk (node:internal/streams/readable:559:12)
team-blue serve:   This error came from the "onResolve" callback registered here:
team-blue serve:     ../../../../node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1281:20:
team-blue serve:       1281 │       let promise = setup({
team-blue serve:            ╵                     ^
team-blue serve:     at setup (file:///D:/usr/htdocs/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:62028:27)
team-blue serve:     at handlePlugins (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1281:21)
team-blue serve:     at buildOrServeImpl (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:970:5)
team-blue serve:     at Object.buildOrServe (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:776:5)
team-blue serve:     at D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:2117:17
team-blue serve:     at new Promise (<anonymous>)
team-blue serve:     at Object.build (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:2116:14)
team-blue serve:     at build (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1963:51)
team-blue serve:     at bundleConfigFile (file:///D:/usr/htdocs/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:61992:26)
team-blue serve:   The plugin "externalize-deps" was triggered by this import
team-blue serve:     vite.config.ts:3:23:
team-blue serve:       3 │ import federation from '@originjs/vite-plugin-federation'
team-blue serve:         ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
team-blue serve: failed to load config from D:\usr\htdocs\vite-plugin-federation\packages\examples\vue3-advanced-demo\team-blue\vite.config.ts
team-blue serve: error when starting preview server:
team-blue serve: Error: Build failed with 1 error:
team-blue serve: ../../../../node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1357:27: ERROR: [plugin: externalize-deps] Failed to resolve entry for package "@originjs/vite-plugin-federation". The package may have incorrect main/module/exports specified in its package.json.
team-blue serve:     at failureErrorWithLog (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1596:15)
team-blue serve:     at D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1052:28
team-blue serve:     at runOnEndCallbacks (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1468:61)
team-blue serve:     at buildResponseToResult (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1050:7)
team-blue serve:     at D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1162:14
team-blue serve:     at responseCallbacks.<computed> (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:697:9)
team-blue serve:     at handleIncomingPacket (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:752:9)
team-blue serve:     at Socket.readFromStdout (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:673:7)
team-blue serve:     at Socket.emit (node:events:520:28)
team-blue serve:     at addChunk (node:internal/streams/readable:559:12)
team-blue serve: Failed
team-red serve: ✘ [ERROR] [plugin externalize-deps] Failed to resolve entry for package "@originjs/vite-plugin-federation". The package may have incorrect main/module/exports specified in its package.json.
team-red serve:     ../../../../node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1357:27:
team-red serve:       1357 │         let result = await callback({
team-red serve:            ╵                            ^
team-red serve:     at packageEntryFailure (file:///D:/usr/htdocs/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:21837:11)
team-red serve:     at resolvePackageEntry (file:///D:/usr/htdocs/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:21834:5)
team-red serve:     at tryNodeResolve (file:///D:/usr/htdocs/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:21572:20)
team-red serve:     at file:///D:/usr/htdocs/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:62039:40
team-red serve:     at requestCallbacks.on-resolve (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1357:28)
team-red serve:     at handleRequest (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:723:19)
team-red serve:     at handleIncomingPacket (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:745:7)
team-red serve:     at Socket.readFromStdout (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:673:7)
team-red serve:     at Socket.emit (node:events:520:28)
team-red serve:     at addChunk (node:internal/streams/readable:559:12)
team-red serve:   This error came from the "onResolve" callback registered here:
team-red serve:     ../../../../node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1281:20:
team-red serve:       1281 │       let promise = setup({
team-red serve:            ╵                     ^
team-red serve:     at setup (file:///D:/usr/htdocs/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:62028:27)
team-red serve:     at handlePlugins (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1281:21)
team-red serve:     at buildOrServeImpl (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:970:5)
team-red serve:     at Object.buildOrServe (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:776:5)
team-red serve:     at D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:2117:17
team-red serve:     at new Promise (<anonymous>)
team-red serve:     at Object.build (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:2116:14)
team-red serve:     at build (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1963:51)
team-red serve:     at bundleConfigFile (file:///D:/usr/htdocs/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:61992:26)
team-red serve:   The plugin "externalize-deps" was triggered by this import
team-red serve:     vite.config.ts:3:23:
team-red serve:       3 │ import federation from "@originjs/vite-plugin-federation"
team-red serve:         ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
team-red serve: failed to load config from D:\usr\htdocs\vite-plugin-federation\packages\examples\vue3-advanced-demo\team-red\vite.config.ts
team-red serve: error when starting preview server:
team-red serve: Error: Build failed with 1 error:
team-red serve: ../../../../node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1357:27: ERROR: [plugin: externalize-deps] Failed to resolve entry for package "@originjs/vite-plugin-federation". The package may have incorrect main/module/exports specified in its package.json.
team-red serve:     at failureErrorWithLog (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1596:15)
team-red serve:     at D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1052:28
team-red serve:     at runOnEndCallbacks (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1468:61)
team-red serve:     at buildResponseToResult (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1050:7)
team-red serve:     at D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:1162:14
team-red serve:     at responseCallbacks.<computed> (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:697:9)
team-red serve:     at handleIncomingPacket (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:752:9)
team-red serve:     at Socket.readFromStdout (D:\usr\htdocs\vite-plugin-federation\node_modules\.pnpm\esbuild@0.16.13\node_modules\esbuild\lib\main.js:673:7)
team-red serve:     at Socket.emit (node:events:520:28)
team-red serve:     at addChunk (node:internal/streams/readable:559:12)
team-red serve: Failed
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by jj19100** [comment]
Solution steps:

1. delete node_modules folder
2. `pnpm add @originjs/vite-plugin-federation@1.4.1`
3. `pnpm restart`

**Comment by s4b0t** [comment]
Maybe "pnpm build" in the root folder will help.
