### ISSUE TITLE
__federation_shared_react-af90d75c.js:60 Uncaught TypeError: Cannot read properties of null (reading 'useRef')     at react_production_min.useRef (__federation_shared_…-af90d75c.js:60:402)     at withSelector_production.useSyncExternalStoreWithSelector (__federation_expose_…c90ac95.js:45589:17)     at useSelector (__federation_expose_…c90ac95.js:45719:27)     at p$K (__federation_expose_…90ac95.js:153270:25)     at Q (__federation_expose_…0ac95.js:165579:114)     at ae (__federation_expose_…ac95.js:165579:1194)

### ISSUE THREAD

**Issue by amiramahmoudatef2020** [originjs/vite-plugin-federation#647]
### Versions

- vite-plugin-federation: 
- vite: 

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

**Comment by amiramahmoudatef2020** [comment]
useRef issue
